services:
  nuxt:
    image: wealth-tracker-nuxt
    pull_policy: never
    container_name: wealth-trucker-nuxt
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env

  db:
    image: postgres:17-alpine3.21
    container_name: wealth-tracker-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: